sudo: false
language: node_js
node_js:
  - "8.11"
cache:
  yarn: true

# exclude tags
branches:
  only:
    - master

env:
  global:
    # build number used by Makefile and Coveralls
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --version

before_script:
  - git diff --exit-code yarn.lock

script:
  - yarn test:ci
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - eval "$(ssh-agent)"
  - echo "$GITHUB_DEPLOY_KEY" > /tmp/github_deploy_key
  - chmod 600 /tmp/github_deploy_key
  - ssh-add /tmp/github_deploy_key
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export GIT_TAG=$(make version) ||
    export GIT_TAG=$(make version)-beta
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export NPM_TAG=latest ||
    export NPM_TAG=beta
  - echo "GIT_TAG=$GIT_TAG"
  - echo "NPM_TAG=$NPM_TAG"
  - >
    [ "${TRAVIS_BRANCH}" != "master" ] &&
    echo "skipping versioning" ||
  - npm version $GIT_TAG -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_JOB_ID"
  - npm publish --tag $NPM_TAG
  - git tag $GIT_TAG -f -a -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_JOB_ID" || true
  - git push --tags git@github.com:$TRAVIS_REPO_SLUG.git

after_success:
  - yarn run storybook-static

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: .storybook-out/
  verbose: true
  on:
    branch: master

